// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeXkvMMyMEXTZp7D-G8PYDPJg2esyGY8U',
    appId: '1:131013840042:web:5f74f0999d5ac5e66514d3',
    messagingSenderId: '131013840042',
    projectId: 'connectflow-e6468',
    authDomain: 'connectflow-e6468.firebaseapp.com',
    storageBucket: 'connectflow-e6468.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFH-fYhBGcN7Z3MuigJM3FDCjM5y3iuQg',
    appId: '1:131013840042:android:208ec1c761419e8e6514d3',
    messagingSenderId: '131013840042',
    projectId: 'connectflow-e6468',
    storageBucket: 'connectflow-e6468.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTzhRTwwZ_bnjEpwGhnVrst0yiyhgF1B4',
    appId: '1:131013840042:ios:1d32dcc3b93349ae6514d3',
    messagingSenderId: '131013840042',
    projectId: 'connectflow-e6468',
    storageBucket: 'connectflow-e6468.firebasestorage.app',
    iosBundleId: 'com.example.connectflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTzhRTwwZ_bnjEpwGhnVrst0yiyhgF1B4',
    appId: '1:131013840042:ios:1d32dcc3b93349ae6514d3',
    messagingSenderId: '131013840042',
    projectId: 'connectflow-e6468',
    storageBucket: 'connectflow-e6468.firebasestorage.app',
    iosBundleId: 'com.example.connectflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeXkvMMyMEXTZp7D-G8PYDPJg2esyGY8U',
    appId: '1:131013840042:web:72495e24772e59f96514d3',
    messagingSenderId: '131013840042',
    projectId: 'connectflow-e6468',
    authDomain: 'connectflow-e6468.firebaseapp.com',
    storageBucket: 'connectflow-e6468.firebasestorage.app',
  );

}